version: '3.8'

services:
  library-db:
    image: postgres:latest
    container_name: library-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/create_schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:      